<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>UUID Generator⚡</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.2.0/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="assets/style.css">

  <link rel="icon" type="image/png" sizes="32x32" href="assets/favicon-thunder-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="assets/favicon-thunder-16x16.png">
</head>

<body>
  <h1>⚡UUID Generator⚡</h1>
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>What is Version 1 UUID?</h2>
        <hr>
        <p>A Version 1 UUID is a universally unique identifier that is generated using a <code>timestamp</code> and the
          <code>MAC address</code> of the computer on which it was generated..</p>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control input-lg" rel="1" data-character-set="a-z,A-Z,0-9,#" readonly>
            <span class="input-group-btn">
              <button type="button" class="btn btn-default btn-lg uuid" name="1">
                <span class="fa fa-refresh"></span>
              </button>
            </span>
          </div>
        </div>
      </div>

      <div class="col-sm-12">
        <h2>What is Version 3 UUID?</h2>
        <hr>
        <p>A Version 3 UUID is a universally unique identifier that is generated by hashing a <code>namespace
            identifier</code> and <code>name</code>. Version 3 uses <a href="https://en.wikipedia.org/wiki/MD5">MD5</a>
          as the hashing algorithm.</p>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control input-lg" rel="3" data-character-set="a-z,A-Z,0-9,#" readonly>
            <span class="input-group-btn">
              <button type="button" class="btn btn-default btn-lg uuid" name="3">
                <span class="fa fa-refresh"></span>
              </button>
            </span>
          </div>
        </div>
      </div>

      <div class="col-sm-12">
        <h2>What is Version 4 UUID?</h2>
        <hr>
        <p>A Version 4 UUID is a universally unique identifier that is generated using <code>random numbers</code>. The
          Version 4 UUIDs produced by this site were generated using a secure random number generator.</p>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control input-lg" rel="4" data-character-set="a-z,A-Z,0-9,#" readonly>
            <span class="input-group-btn">
              <button type="button" class="btn btn-default btn-lg uuid" name="4">
                <span class="fa fa-refresh"></span>
              </button>
            </span>
          </div>
        </div>
      </div>

      <div class="col-sm-12">
        <h2>What is Version 5 UUID?</h2>
        <hr>
        <p>A Version 5 UUID is a universally unique identifier that is generated by hashing a <code>namespace
            identifier</code> and <code>name</code>. Version 5 uses <a
            href="https://en.wikipedia.org/wiki/SHA-1">SHA-1</a> as the hashing algorithm.</p>
      </div>

      <div class="col-sm-12">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control input-lg" rel="5" data-character-set="a-z,A-Z,0-9,#" readonly>
            <span class="input-group-btn">
              <button type="button" class="btn btn-default btn-lg uuid" name="5">
                <span class="fa fa-refresh"></span>
              </button>
            </span>
          </div>
        </div>
      </div>

      <div class="col-sm-12">
        <hr>
        <p class="text-center">For more information, you can check out <a href="https://tools.ietf.org/html/rfc4122" target="_blank">UUID Docs</a> and 
          <a href="https://en.wikipedia.org/wiki/Universally_unique_identifier" target="_blank">UUID Wikipedia</a>.</p>
      </div>
    </div>
  </div>

  <footer class="page-footer font-small mdb-color darken-3 pt-4">
    <div class="footer-copyright text-center py-3">By
      <a href="https://github.com/furkankahvecii" target="_blank"> Furkan Kahveci</a>
    </div>
  </footer>

</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="assets/script.js"></script>
</html>